### ISSUE TITLE
Achieving peak depth frame rate

### ISSUE THREAD

**Issue by YoniSmolin** [xlz/libfreenect2#2]
Hi xlz,

I'm using JetsoHacks' fork of your fork of libfreenect2. Thanks a lot for sharing this with us.

My goal is to obtain a depth stream at as a high rate as possible. The "CudaDepthPacketProcessor" reports a frame rate of ~75Hz but the the frame listener in my app produces new frames at only ~30Hz.

Can you give me some advice for getting closer to the desired peak rate ??

Thanks in advance.

**Comment by xlz** [comment]
30Hz is the maximum actual frame rate of Kinect 2. 75Hz = 13 msec, a performance metric which means it is idle for 20 msec between each frame, and other computation can utilize the resources.
