### ISSUE TITLE
Unable to make libfreenect2 on TK1

### ISSUE THREAD

**Issue by anshulvj** [xlz/libfreenect2#3]
cmake finishes with some unrelated warnings. 
make fails with error:

```
 [ 97%] Building CXX object CMakeFiles/freenect2.dir/src/cuda_depth_packet_processor.cpp.o
Linking CXX shared library ../lib/libfreenect2.so
CMakeFiles/freenect2.dir/src/cuda_depth_packet_processor.cpp.o: In function `libfreenect2::loadBufferFromResources(std::string const&, unsigned char*, unsigned int)':
/home/ubuntu/xlzlibfreenect2/libfreenect2/examples/protonect/src/cuda_depth_packet_processor.cpp:50: multiple definition of `libfreenect2::loadBufferFromResources(std::string const&, unsigned char*, unsigned int)'
CMakeFiles/freenect2.dir/src/opencl_depth_packet_processor.cpp.o:/home/ubuntu/xlzlibfreenect2/libfreenect2/examples/protonect/src/opencl_depth_packet_processor.cpp:58: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [../lib/libfreenect2.so] Error 1
make[1]: *** [CMakeFiles/freenect2.dir/all] Error 2
make: *** [all] Error 2 `
```

I followed instructions from https://github.com/xlz/libfreenect2/wiki/Jetson-TK1-HOWTO
This is a newly flashed TK. After flashing I installed libfreenect2 (not xlz/libfreenect2) but it was not giving me any depth/ir/color output so I created a new dir for xlz/libfreenect2 and attempted a fresh install. Any idea what could be going on? I saw a similar issue https://github.com/OpenKinect/libfreenect2/issues/157 but I'm not sure I saw a solution.

Thanks

**Comment by xlz** [comment]
>  installed libfreenect2 (not xlz/libfreenect2) but it was not giving me any depth/ir/color output

Recently I tested upstream libfreenect2 with OpenGL and TurboJpeg on Jetson. It did run, albeit slowly. It should run for you. Let's go from there.

This is indeed a bug, but its relevance is almost none. A while ago I fixed this bug in upstream preparing to integrate CUDA processor into upstream https://github.com/OpenKinect/libfreenect2/commit/0f80e61115a2244eeb897e434c42de4bdc0b9467. But I got involved in other stuff at upstream and am busy getting 0.1 release published.

A simple workaround for you: `cmake -DENABLE_OPENCL=OFF`.
